version: '2'

services:
  mysql:
    container_name: ertmysql
    image: mysql:5.7.23
    ports:
      - 6000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ert
      - MYSQL_USER=ert
      - MYSQL_PASSWORD=ert
    volumes:
      - ./data/:/var/lib/mysql
      - ./startup_scripts/:/docker-entrypoint-initdb.d
